[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
decorations = "None"
option_as_alt = "Both"
# opacity = 0.9

[font]
normal.family = "JetBrainsMono Nerd Font"
# normal.family = "SF Mono"
size = 15

[general]
import = [
    #"~/.config/alacritty/gruvboxdark.toml" # Gruvbox Dark
    #~/.config/alacritty/everforest.toml"  # Everforest
    "~/.config/alacritty/solarizeddark.toml" # Solarizeddark
    
]
